title: "RCL Learn Docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
  "RCL Learn Docs on GitHub":
    - "https://github.com/rcl-learn/docs"
callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red